# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/image_analysis',
                'doc_host': 'https://apingali.github.io',
                'git_url': 'https://github.com/apingali/image_analysis',
                'lib_path': 'image_analysis'},
  'syms': {'image_analysis.core': {'image_analysis.core.foo': ('core.html#foo', 'image_analysis/core.py')}}}
